baseurl = "/"
Paginate = 5

[params]
  env = "development"

[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"


# datocms:start
title = "Berxi"
languageCode = "en"
# datocms:end